# Generated by Django 5.1.5 on 2025-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
